use_frameworks!

platform :ios, '8.0'

target 'YLCategroy_Example' do
  pod 'YLCategroy', :path => '../'

  target 'YLCategroy_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
